### ISSUE TITLE
Setup.rb 404 error

### ISSUE THREAD

**Issue by senn101** [hhyyrylainen/Leviathan#43]
I'm a little inexperienced, so I'm not sure if its something I'm doing wrong, but when I try to compile Leviathan by running Setup.rb, I run into a problem. Once it reaches the part where it tries to clone CEF, it encounters a 404 Not Found error. I think the problem is that it is trying to clone CEF from boostslair.com, which doesn't exist. I don't think Setup.rb is out of date or anything, because I just cloned Leviathan less than an hour ago. Is there something else I should be doing?

**Comment by hhyyrylainen** [comment]
The link is working fine for me: https://boostslair.com/rubysetupsystem/deps/cef_binary_3.3497.1837.g00188c7_linux64_minimal.7z

The latest version is on the `develop` branch. So if you are on master that's an issue.

**Comment by senn101** [comment]
Yep, I was on master. Looks like develop is working out. Thanks so much!
