### ISSUE TITLE
engine refuses to compile

### ISSUE THREAD

**Issue by ichabodphage** [hhyyrylainen/Leviathan#44]
tried to compile the engine but it gave me this error code
ERROR: Downloaded file hash doesn't match expected hash, 4960c8f5c4fc5829958adae0c64904c0290569c815ef93d15ee5ca05b4206b4d != 50076ddb0225a7eb440bbb67ac07d74186068a31be2c796a6920beeea446e68b

**Comment by hhyyrylainen** [comment]
Use the `develop` branch. Master is out of date with the dependencies.
